apiVersion: v1
kind: Service
metadata:
  name: aplikasi-demo-service
  namespace: default
spec:
  # Gunakan NodePort agar mudah diakses di Minikube
  type: NodePort 
  selector:
    app: aplikasi-demo # HARUS COCOK dengan 'matchLabels' di Deployment
  ports:
  - protocol: TCP
    port: 80 # Port yang akan diekspos oleh Service
    targetPort: 8080 # Port container (dari server.js)
